[web] Item page creation
victorbillaud/tomato pull request #35
Opened 2023-11-20 15:37 UTC by victorbillaud

What's added in this pr ?
- Add scan types to table scans (see issue #34)
- Declare item as lost and found
- Item page with necessary infos
- Update item properties (name, description)
- See scan history of this item

![Screenshot 2023-11-20 at 16 36 37](https://github.com/victorbillaud/tomato/assets/61359041/3b86c224-8bdc-4ae2-9d35-b0e737760648)
![IMG_6831](https://github.com/victorbillaud/tomato/assets/61359041/4ab6afe5-3945-4673-90eb-e7adcdd7429a)
![IMG_6830](https://github.com/victorbillaud/tomato/assets/61359041/324ad450-6a4e-4523-ba0a-304c6a1cd63d)

2023-11-21 10:31 UTC, Arthur-PI requested changes
Pas grand chose à dire, plus des commentaire que des suggestions mais noice

2023-11-21 10:31 UTC, Arthur-PI commented on web/app/dashboard/item/[item_id]/page.tsx
> +  revalidatePath(`/dashboard/item/${item.id}`);
ça sert à quoi ça ?

2023-11-21 10:31 UTC, Arthur-PI commented on web/app/dashboard/item/[item_id]/page.tsx
> +  });
Là tu mets lost à true mais tu mets pas found à false, ça veut dire qu'un item peut etre lost & found en meme temps 🥸.
(aussi enlever la found_at)

2023-11-21 10:34 UTC, victorbillaud commented on utils/lib/scan/services.ts
> +        type: scan.type ? [...scan.type, userType] : [userType],
tqt j'ai capté ce que tu veux dire

2023-11-21 10:35 UTC, victorbillaud commented on web/app/dashboard/item/[item_id]/page.tsx
> +  revalidatePath(`/dashboard/item/${item.id}`);
C'est pour recharger la page coté serveur avant de rediriger. C'est pour refresh coté serveur [ici](https://nextjs.org/docs/app/api-reference/functions/revalidatePath)

2023-11-21 19:30 UTC, victorbillaud commented on web/app/dashboard/item/[item_id]/page.tsx
> +  });
Dcp j'ai delete les deux

2023-11-21 19:32 UTC, victorbillaud commented on utils/lib/scan/services.ts
> +        type: scan.type ? [...scan.type, userType] : [userType],
Tu peux voir cette superbe function postgres avec un magnifique trigger ;) 
https://github.com/victorbillaud/tomato/blob/fea9da089d1f2c6b0f2aa52990062691c4b6680c/supabase/migrations/20231121192834_scan_type.sql#L11-L43

2023-11-22 11:18 UTC, Arthur-PI commented on utils/lib/scan/services.ts
> +        type: scan.type ? [...scan.type, userType] : [userType],
AHAHAHAHHAAH bien joué (Chad move)

2023-11-22 11:19 UTC, Arthur-PI commented on web/app/dashboard/item/[item_id]/page.tsx
> +  revalidatePath(`/dashboard/item/${item.id}`);
Ok bien vu

2023-11-22 11:19 UTC, Arthur-PI commented on web/app/dashboard/item/[item_id]/page.tsx
> +  });
Carré

2023-11-22 11:22 UTC, Arthur-PI approved these changes
J'aime bien.
J'aime beaucoup.

2023-11-22 11:24 UTC, merged