Web/messaging
victorbillaud/tomato pull request #49
Opened 2023-11-27 14:43 UTC by Tomspace900

2023-12-05 12:27 UTC, victorbillaud requested changes

2023-12-05 12:27 UTC, victorbillaud commented on web/components/chat/ChatCard.tsx
> +      </div>
Little border could be nice

2023-12-05 12:27 UTC, victorbillaud commented on web/components/chat/ChatCard.tsx
> +          {conversation.last_message?.content || '(empty)'}
I think you don't need to show empty, it look weird

2023-12-05 12:27 UTC, victorbillaud commented on web/components/chat/Input.tsx
This component should be client
- separate the server action in another file
- bind an argument `conversation_id`, look [this](https://nextjs.org/docs/app/api-reference/functions/server-actions#binding-arguments)
- Send the form from the client and reset the input value with a ref

2023-12-05 12:27 UTC, victorbillaud commented on web/components/chat/Message.tsx
> +};
Rendering error on big messages 
![Screenshot 2023-12-05 at 13 08 45](https://github.com/victorbillaud/tomato/assets/61359041/9dd7879d-13ca-4822-90f7-273ab959465e)

2023-12-05 12:27 UTC, victorbillaud commented on web/components/chat/Chat.tsx
> +  const renderMessages = () => {
use `useMemo` for performance

2023-12-05 12:27 UTC, victorbillaud commented on web/components/chat/Chat.tsx
> +
Nothing to do here for me

2023-12-05 12:27 UTC, victorbillaud commented on web/components/chat/Chat.tsx
Realtime doesnt work for both sides

https://github.com/victorbillaud/tomato/assets/61359041/14ae02e6-8991-47e0-a120-985e8cd65a5e

2023-12-05 16:18 UTC, victorbillaud commented on web/components/chat/Chat.tsx
> +
Yes but i should not be in the renderMessage functions, it should be in the return statement of the component

2023-12-10 19:25 UTC, victorbillaud requested changes
La logique est mieux, quelques modifs encore et on sera pas mal. Il y aura de quoi faire une autre pr pour opti tous ça

2023-12-10 19:25 UTC, victorbillaud commented on web/app/chat/layout.tsx
pas besoin de page cliente ici

2023-12-10 19:25 UTC, victorbillaud commented on web/app/chat/page.tsx
ici non plus

2023-12-10 19:25 UTC, victorbillaud commented on web/app/chat/[conversation_id]/page.tsx
Je ne vois pas l’intérêt d'avoir cette page en cliente. Tu as fais le choix de passer les vieux messages à ton contexte pour qu'il s'occupe seulement des nouveaux messages. Donc ici tu peux tous charger en serveur

2023-12-10 19:25 UTC, victorbillaud commented on web/components/chat/Chat.tsx
> +    });
ca tu peux le mettre dans le corps du useMemo tu va gagner en perf

2023-12-10 19:25 UTC, victorbillaud commented on web/components/chat/ChatCard.tsx
On va rien changer ici mais il faudra revoir les perfs de ce composants parce que c'est pas opti

2023-12-10 19:25 UTC, victorbillaud commented on web/components/chat/ChatContext.tsx
> +          table: 'message',
Ici tu peux ajouter un filter pour ecouter que les conversations souhaitées 
`filter: 'conversation_id=in.(id_1, id_2, etc)',`

2023-12-10 19:25 UTC, victorbillaud commented on web/components/chat/ChatContext.tsx
> +          table: 'message',
parce que la tu ecoutes les messages de tous le monde

2023-12-10 19:25 UTC, victorbillaud commented on web/components/chat/ChatList.tsx
> +    async function fetchConversation(supabase: any, userFetched: User) {
```suggestion
    async function fetchConversations(supabase: any, userFetched: User) {
```

2023-12-10 19:25 UTC, victorbillaud commented on web/components/chat/MobileHeader.tsx
Pareil ici tu fetch des données alors que tu pourrais tous fetch dans ta page serveur et le passer en props ici

2023-12-11 19:11 UTC, Tomspace900 commented on web/components/chat/ChatCard.tsx
Ok, j'ai rien touché ici du coup, mais je note

2023-12-11 19:52 UTC, victorbillaud requested changes
Aller dernier round de review et on y est

2023-12-11 19:52 UTC, victorbillaud commented on utils/lib/messaging/services.ts
> +
Ici tu join l'item relié à la conversation mais tu ne récupères mêmes pas les champs de conversation donc autant fetch directement l'item avec le service getItem

2023-12-11 19:52 UTC, victorbillaud commented on web/app/chat/page.tsx
Pour moi ici tu n'as pas meme pas besoin d'afficher le chat, on est pas dans une conversation et on le sait donc tu va déclencher une logique pour rien. Tu pourrais afficher directement selectionner une conversation.

2023-12-11 19:52 UTC, victorbillaud commented on web/components/chat/Chat.tsx
> +  }
Ici tu pourrais call le notFound() de nextjs et creer une page not-found.tsx pour afficher le Conversation not found please select a valid one in the list

2023-12-11 19:52 UTC, victorbillaud commented on web/components/chat/ChatContext.tsx
> +          filter: 'conversation_id=in.(' + conversationsIds.join(',') + ')',
```suggestion
         filter: `conversation_id=in.(${conversationsIds.join(',')})`
```

2023-12-11 19:52 UTC, victorbillaud commented on web/components/chat/ChatList.tsx
> +  }, [supabase]);
Tout ca tu peux l'éviter en faisant les requêtes dans le layout et pas ici

2023-12-11 19:55 UTC, Tomspace900 commented on utils/lib/messaging/services.ts
> +
Ouai mais justement j'ai besoin de la conversation pour avoir l'id de l'item

2023-12-11 19:58 UTC, victorbillaud commented on utils/lib/messaging/services.ts
> +
Alors il faut rename la fonction getConversationItem

2023-12-11 20:00 UTC, Tomspace900 commented on utils/lib/messaging/services.ts
> +
(c'est ce que j'avais proposé et t'as corrigé sale fou)
Ok mec pas d'soucis !

2023-12-11 20:02 UTC, victorbillaud commented on utils/lib/messaging/services.ts
> +
Parce que je pensais que tu avais besoin d'avoir les champs de la conversation donc c'etait logique

2023-12-12 13:00 UTC, merged